In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

print(arr[0:2, 2])

[7 8 9]
[3 8]


the above for slicing

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

print(arr[4:])

print(arr[:4])

print(arr[-3:-1])

print(arr[1:5:2])

print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


To check dimensions

In [3]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [4]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

print(np.sum(arr))

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])

2
7
10
7


In [5]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [6]:
arr_1 = np.array([1, 2, 3, 4, 5])
y = arr_1.view()
arr_1[0] = 42

print(arr_1)
print(y)

[42  2  3  4  5]
[42  2  3  4  5]


the above is copy vs view

In [7]:
arr_2 = np.array([1, 2, 3, 4, 5])

a = arr_2.copy()
b = arr_2.view()

print(a.base)
print(b.base)

None
[1 2 3 4 5]


In [8]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


arr = np.array([1,2,3,4,5])

print(arr.dtype)

arr = np.array([True, False, True])

print(arr.dtype)

arr = np.array([1+2j, 3+6j, 7+10j])

print(arr.dtype)


arr = np.array([1.0,2.0,3.0,4.0,5.0])
print(arr.dtype)

try:
    arr = np.array([1 + 2j, 0,"te"])
except Exception as e:
    print(e)

arr = np.array(['1', '2', '3'], dtype='i')
print(arr.dtype)


arr = np.array([1.1, 2.1, 3.1])
print(arr)
print(arr.dtype)

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

arr = np.array([-2, -1, 0, 1, 2])
newarr = arr.astype(bool)
print(newarr)

<U6
int64
bool
complex128
float64
int32
[1.1 2.1 3.1]
float64
[1 2 3]
int32
[ True  True False  True  True]


In [9]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


print(np.__version__)


arr_0d = np.array(42)

print(arr_0d)

arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.23.5
42
[1 2 3 4 5]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(type(arr))


arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr_3)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
