In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 6,9,8,6])

x = np.where(arr == 6)

print(x) 

(array([5, 6, 9]),)


In [3]:
x = np.where(arr == 3)

print(x) 

(array([2]),)


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

x = np.where(arr%2 == 0) # finding odd numbers

print(x) 

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),)


In [6]:
x = np.where(arr%2 != 0) # finding even numbers

print(x) 

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),)


In [7]:
arr = np.array([6, 7, 8, 9, 7, 7, 9, 10, 7])

x = np.searchsorted(arr, 7)

print(x) 

1


In [8]:
x = np.searchsorted(arr, 10)

print(x) 

7


In [9]:
x = np.searchsorted(arr, 7, side='right')

print(x) 

6


In [10]:
x = np.searchsorted(arr, 1, side='right')

print(x) 

0


In [11]:
x = np.searchsorted(arr, 10, side='right')
print(x) 

9


In [12]:
arr = np.array([1, 3, 5, 7, 9, 6])

x = np.searchsorted(arr, [2, 4, 6])

print(x) 

[1 2 3]


In [13]:
print(arr)

[1 3 5 7 9 6]


In [14]:
import numpy as np
arr = np.array([13, 39, 11, 46])
x = np.where(arr%2 == 1)
print(x)

(array([0, 1, 2]),)
