In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

In [2]:
print(arr1)

[1 2 3]


In [3]:
print(arr2)

[4 5 6]


In [5]:
print(arr)

[1 2 3 4 5 6]


In [6]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [7]:
arr_ax_0 = np.concatenate((arr1, arr2), axis=0)
print(arr_ax_0)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
arr_ax_m_1 = np.concatenate((arr1, arr2), axis=-1) # same as 1
print(arr_ax_m_1)

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
arr_ax_m_0 = np.concatenate((arr1, arr2), axis=-2) # same as 0
print(arr_ax_m_0)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining using stack

In [10]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [12]:
print(arr1.ndim, arr2.ndim)

1 1


In [13]:
arr = np.stack((arr1, arr2), axis=2)
print(arr) # throws error

AxisError: axis 2 is out of bounds for array of dimension 2

In [15]:
arr_1 = np.stack((arr1, arr2), axis=-1)


In [17]:
print(arr_1)

[[1 4]
 [2 5]
 [3 6]]


In [18]:
arr_2 = np.stack((arr1, arr2), axis=-2)

In [19]:
print(arr_2)

[[1 2 3]
 [4 5 6]]


Using hstack

In [27]:
arr_h = np.hstack((arr1, arr2))

In [28]:
print(arr_h)

[1 2 3 4 5 6]


Using Vstack

In [29]:
arr_h = np.vstack((arr1, arr2))

In [30]:
print(arr_h)

[[1 2 3]
 [4 5 6]]


In [26]:
arr_d = np.dstack((arr1, arr2))
print(arr_d)

[[[1 4]
  [2 5]
  [3 6]]]


In [31]:
print(arr1)
print(arr2)

[1 2 3]
[4 5 6]
